-- Schema of the request management service.
-- Written in portable SQL: it runs on H2 as well as on PostgreSQL.

CREATE TABLE request (
    id                  UUID          NOT NULL,
    name                VARCHAR(200)  NOT NULL,
    body                VARCHAR(10000) NOT NULL,
    state               VARCHAR(32)   NOT NULL,
    publication_number  BIGINT,
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_modified_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version             BIGINT        NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT uq_request_publication_number UNIQUE (publication_number)
);

CREATE INDEX idx_request_state ON request (state);
CREATE INDEX idx_request_created_at ON request (created_at);

CREATE TABLE request_state_change (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    request_id       UUID          NOT NULL,
    sequence_number  INTEGER       NOT NULL,
    from_state       VARCHAR(32),
    to_state         VARCHAR(32)   NOT NULL,
    action           VARCHAR(32),
    reason           VARCHAR(500),
    occurred_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_request_state_change PRIMARY KEY (id),
    CONSTRAINT fk_state_change_request FOREIGN KEY (request_id) REFERENCES request (id),
    CONSTRAINT uq_state_change_sequence UNIQUE (request_id, sequence_number)
);

CREATE INDEX idx_state_change_request ON request_state_change (request_id);

-- Source of the unique numeric identifier assigned on publication.
CREATE SEQUENCE publication_number_seq START WITH 1 INCREMENT BY 1;
